export default {
	ships: 'Ships:',
	score: 'Score:',
	title: 'Invaders',
	play: 'Play game',
	highScores: 'High scores',
	options: 'Options',
	back: 'Back',
	sound: 'Sound: ',
	showFPS: 'Show FPS: ',
	on: 'On',
	off: 'Off',
	paused: 'Paused',
	pressToContinue: 'Press [space] to continue',
	tapToContinue: 'Tap to continue',
	controls: 'Controls: ',
	buttons: 'buttons',
	drag: 'drag',
	gyro: 'gyro',
	dragToMove: 'Drag to move',
	tiltToMove: 'Tilt screen to move'
};
